# Generated by Django 4.1.3 on 2022-11-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abbreviationApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abbreviation',
            name='information',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
